default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fb_login_development
test:
  <<: *default
  database: fb_login_test
production:
  <<: *default
  database: fb_login_production
  username: fb_login
  password: <%= ENV['FB_LOGIN_DATABASE_PASSWORD'] %>
